### ISSUE TITLE
PUD altitude unit : README

### ISSUE THREAD

**Issue by martinroger** [matthewlloyd/bebop#1]
Hi Matthew,

I think you may be wrong in your README file about the altitude unit. I've been parsing a few puds, and I do believe that the unit rather is in mm instead of cm. Keeping it in cm renders ludicrous altitudes (500m for an actual 50m high flight) that do not match what is given by Drone Academy for the same flight.

**Comment by matthewlloyd** [comment]
Thanks Martin - fixed!

**Comment by martinroger** [comment]
Any time! :)
